### ISSUE TITLE
企业微信版本过低

### ISSUE THREAD

**Issue by 3218923350** [hanfangyuan4396/dify-on-wechat#114]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

由于企业微信要用到ntwork，ntwork又只支持企业微信4.0.8.6027，可是企业微信4.0.8.6027扫码登录时，会出现“当前副设备的企业微信版本较低，请更新副设备版本后再式”的提示。感觉就是企业微信限制了低版本登录。那这该如何使用企业微信呢

**Comment by hanfangyuan4396** [comment]
企业微信依赖ntwork支持，目前ntwork不再维护，只能尝试降低手机企业微信的版本或者更换其他企业微信号尝试登录
