### ISSUE TITLE
当dify工作流返回数据为空的时候，wx中返回结果为{}

### ISSUE THREAD

**Issue by ccsert** [hanfangyuan4396/dify-on-wechat#119]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的dify-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

# 背景
在私聊场景下，我期望工作流通过一些关键字进行触发，才进行执行，但是目前没看到相关的方案，所以我在dify工作流中通过条件分支进行判断，仅有包含具体关键字的时候才调用llm节点进行返回内容，而不包含关键字的分支则返回结果为空.
# 触发情况
在上述的场景中，当微信私聊用户，未输入相关关键字，此时工作流会进入返回空的分支，反应到微信返回结果的情况则是回复了一个{} json的花括号对象,实际日志内的结果就是 content={} 最后将{}直接返回了

### 问题描述 😯

![image](https://github.com/user-attachments/assets/cbddf0c5-9c09-4468-8719-42c704f05f73)
上图是回复的结果

### 终端日志 📒

```log
Start auto replying.
[INFO][2024-10-17 20:19:22][bridge.py:73] - create bot dify for chat
[INFO][2024-10-17 20:19:22][dify_bot.py:34] - [DIFY] query=ni hao
[INFO][2024-10-17 20:19:24][wechat_channel.py:246] - [WX] sendMsg=Reply(type=TEXT, content={}), receiver=@2b2c6fc5ee29000d7e071d3109be9576
[INFO][2024-10-17 20:19:35][dify_bot.py:34] - [DIFY] query= 张三，1984年2月24日下午3点，男
[INFO][2024-10-17 20:19:37][wechat_channel.py:246] - [WX] sendMsg=Reply(type=TEXT, content={}), receiver=@2b2c6fc5ee29000d7e071d3109be9576
[INFO][2024-10-17 20:21:31][dify_bot.py:34] - [DIFY] query=xxxxxx
[INFO][2024-10-17 20:21:33][wechat_channel.py:246] - [WX] sendMsg=Reply(type=TEXT, content={}), receiver=@2b2c6fc5ee29000d7e071d3109be9576
```

**Comment by hanfangyuan4396** [comment]
感谢pr
