### ISSUE TITLE
企微版本太低

### ISSUE THREAD

**Issue by Nomia-Monamour** [hanfangyuan4396/dify-on-wechat#130]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的dify-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 复现步骤 🕹

启动企业微信

### 问题描述 😯

企业微信版本太低，作者可不可以换一个类似于ntwork的，目前企微确实已经增加了旧版本识别，目前企微这个路确实走不通了，今天切换了双端的企微版本，都降低了还是没用。所有的方案都试过了都没用。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by hanfangyuan4396** [comment]
尝试更换企业微信号，不再维护此功能
