### ISSUE TITLE
增加chatflow模式，可以让机器人拥有记忆模式

### ISSUE THREAD

**Issue by chiefluo** [hanfangyuan4396/dify-on-wechat#138]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

可以增加chatflow模式吗？按照现在dify的发展，最强大的是chatflow的机器人，因为只有这个机器人具有记忆功能，其他模式都没有记忆功能

**Comment by hanfangyuan4396** [comment]
dify_app_type: chatbot 配置覆盖了chatflow，即工作流编排
![image](https://github.com/user-attachments/assets/65a63a5f-48e6-4602-8f6c-7c9af499e82f)

**Comment by chiefluo** [comment]
好的，谢谢，还有一个问题已经提交，是部署能连接，但是显示“我现在遇到一些问题，请您稍后再试”，我用了docker部署和不用docker都是一样的报错，目前的dify版本是0.10.0

**Comment by chiefluo** [comment]
> 好的，谢谢，还有一个问题已经提交，是部署能连接，但是显示“我现在遇到一些问题，请您稍后再试”，我用了 docker 部署和不用 docker 都是一样的报错，目前的dify版本是0.10.0
