### ISSUE TITLE
gewechat channel启动失败

### ISSUE THREAD

**Issue by hanfangyuan4396** [hanfangyuan4396/dify-on-wechat#148]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.10

### 使用的dify-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 问题描述 😯

在启动gewechat channel时需要先启动回调服务器，再设置回调地址，需要修改下方代码
![8a145302ee2484cdf8ed11ac4d31ac7](https://github.com/user-attachments/assets/d03e713b-3a4b-431f-b373-e3455ea215fd)

### 终端日志 📒

<img width="1304" alt="2dae07c021f39f9bf3b8afe80108b59" src="https://github.com/user-attachments/assets/f6918ef9-3b77-49e8-9430-30f060788296">

**Comment by liguoyu666** [comment]
为啥我最新的代码还是报这个错啊，看代码也修改了的啊，回调地址也显示在运行中
