### ISSUE TITLE
如何在个人对话中重新开启一个会话

### ISSUE THREAD

**Issue by skywolf123** [hanfangyuan4396/dify-on-wechat#166]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在个人对话中接入dify的chatbot，一直对话会都在一个会话中，会一直使用历史记录，如何新开一个会话呢
比如config.json中可以配置一个触发词，用于新建会话

**Comment by hanfangyuan4396** [comment]
发送 #reset

**Comment by hanfangyuan4396** [comment]
![image](https://github.com/user-attachments/assets/9c6857c6-a3a8-4e76-b26a-250f6db02d80)
