### ISSUE TITLE
为什么我配置好了coze了却使用不了，然后后台提示我bot没有发布到api渠道，但是我已经发布了

### ISSUE THREAD

**Issue by He0607** [hanfangyuan4396/dify-on-wechat#24]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.9

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 终端日志 📒

```log
<[INFO][2024-04-28 17:09:50][bytedance_coze_bot.py:25] - [COZE] query=在吗
[WARNING][2024-04-28 17:09:50][chat_gpt_session.py:84] - num_tokens_from_messages() is not implemented for model coze. Returning num tokens assuming gpt-3.5-turbo.
[ERROR][2024-04-28 17:09:51][bytedance_coze_bot.py:32] - [COZE] reply error=[COZE] Error: 当前 Bot 未发布到 Bot as API 渠道
[INFO][2024-04-28 17:09:51][wechat_channel.py:253] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我暂时遇到了一些问题，请您稍后重试~), receiver=@@a57563e28f446376019882b929d7f09fb153eeb8e20deff3385289d9db810a0b>
```

**Comment by hanfangyuan4396** [comment]
国内的coze吗，从报错来看coze的接口已经返回内容了，所以大概率不是本项目的问题，是coze机器人api没配置好

**Comment by He0607** [comment]
> 国内的coze吗，从报错来看coze的接口已经返回内容了，所以大概率不是本项目的问题，是coze机器人api没配置好

我用的是外版的coze，这个我在其他方法测试的我的bot跟api是可以用的

**Comment by He0607** [comment]
> 方便把接口curl私发给我吗，这个需要我本地调试一下，微信hanfangyuan12138
> [……](#)
> ---- 回复的原邮件 ---- |发件人 | ***@***.***> | |日期 | 2024年04月29日 08:50 | |营养 | ***@***.***> | |抄送至|韩***@***.***>***@***.***> | |主题 |回复: [hanfangyuan4396/dify-on-wechat]我配置好了coze了却用不了，然后为什么提示我bot没有发布到api渠道，但是我已经发布了（问题#24）|国内的coze吗，从报错看coze的接口已经返回内容了，所以很大概率不是本项目的问题，是coze机器人api没配置好我用的是外版的coze，这个我在其他方法测试的我的bot跟api是可以用的——直接回复此电子邮件，在GitHub上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：***@***.***>

好的这边加你了

**Comment by Linnnkkk** [comment]
请问如何解决的？@

> > 方便把接口curl私发给我吗，这个需要我本地调试一下，微信hanfangyuan12138
> > [……](#)
> > ---- 回复的原邮件 ---- |发件人 | _**@**_._**> | |日期 | 2024年04月29日 08:50 | |营养 | _**@**_.**_> | |抄送至|韩***@_**.**_>_**@**_._**> | |主题 |回复: [hanfangyuan4396/dify-on-wechat]我配置好了coze了却用不了，然后为什么提示我bot没有发布到api渠道，但是我已经发布了（问题#24）|国内的coze吗，从报错看coze的接口已经返回内容了，所以很大概率不是本项目的问题，是coze机器人api没配置好我用的是外版的coze，这个我在其他方法测试的我的bot跟api是可以用的——直接回复此电子邮件，在GitHub上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：**_@_**.**_>
> 
> 好的这边加你了
