### ISSUE TITLE
有的微信账号扫码之后报错

### ISSUE THREAD

**Issue by y61235** [hanfangyuan4396/dify-on-wechat#61]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Linux

### 运行的python版本是?

python 3.7

### 使用的dify-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

youdiandian61235 微信号扫码

### 问题描述 😯

Please press confirm on your phone.
[ERROR][2024-07-29 20:00:04][wechat_channel.py:156] - 'wxsid'

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by y61235** [comment]
新微信账号会报这个错误，需要认证。认证之后解决了。

**Comment by hanfangyuan4396** [comment]
wxsid 错误需要 微信实名认证

**Comment by myzf** [comment]
试了是实名认证问题
