### ISSUE TITLE
后台不断循环弹出登陆二维码和链接

### ISSUE THREAD

**Issue by mingtian886** [hanfangyuan4396/dify-on-wechat#88]
后台不断循环弹出登陆二维码和链接，影响正常日志查看

**Comment by sushushu** [comment]
我也是这样

**Comment by mingtian886** [comment]
期待大佬早日解决

**Comment by mingtian886** [comment]
@hanfangyuan4396

**Comment by hanfangyuan4396** [comment]
请问是通过web ui启动的才出现这种现象吗

**Comment by hanfangyuan4396** [comment]
请提供一下弹出二维码前后完整的日志吧，我没有复现

**Comment by mingtian886** [comment]
> 请提供一下弹出二维码前后完整的日志吧，我没有复现

python源码启动

**Comment by hanfangyuan4396** [comment]
提供一下弹出二维码前后完整的日志吧，我需要看一下重启的原因

**Comment by michael-xgw** [comment]
> 提供一下弹出二维码前后完整的日志吧，我需要看一下重启的原因 @mingtian886

先是出现 Unexpected sync check result: window.synccheck={retcode:"1102",selector:"0"} ，然后手机端会看到“桌面微信已退出”，然后日志中就会不断弹出二维码让重新扫码

![image](https://github.com/user-attachments/assets/0b67ac7f-d013-4301-b780-9ecf2bfe5311)

**Comment by hanfangyuan4396** [comment]
其实是掉线了，掉线之后会重新让你扫码登录，如果你一直没有扫码，二维码会过期，重新下载新的

**Comment by michael-xgw** [comment]
嗯，是因为手机端长时间退出，所以导致web端掉线了

**Comment by nolynn** [comment]
我也是如此；

**Comment by ios-xxx** [comment]
我也是，出现了上面的问题
