### ISSUE TITLE
 如何在企业微信的第三方应用里添加我本地部署的dify？

### ISSUE THREAD

**Issue by nekoy1985** [hanfangyuan4396/dify-on-wechat#97]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

在说明文档中没有找到，我不想通过laf，而是本地的dify。
我使用了公网的地址填写到企业微信的第三方应用的API接收消息里，但是会报错【openapi回调地址请求不通过】。
似乎需要做一些环境变量的设置才可以？

**Comment by zzzer1** [comment]
请问怎么实现的，有没有相关教程分享一下，谢谢
